config:
  ponzi_ast_location: './Ponzi_Abstract_Syntax_Trees'
  not_ponzi_ast_location: './Not_Smart_Ponzi_AST'
  not_smart_ponzi_source_code: './Not_Smart_Ponzi_Source_Code'
  smart_ponzi_source_code: './ast_generator/Smart_Ponzi'
  ponzi_csv: './Docs/ponzi.csv'
  not_ponzi_csv: './Docs/not_ponzi.csv'
  contracts_csv: './Docs/contracts.csv'
  contracts2_csv: './Docs/contracts2.csv'
  not_ponzi_semantic_documents: './Docs/Not_Ponzi_Semantic_Documents'
  ponzi_semantic_documents: './Docs/Ponzi_Semantic_Documents'
  most_used_in_ponzies: './Docs/Most_used_terms_in_Ponzies.txt'
  most_used_in_not_ponzies: './Docs/Most_used_terms_in_Not_Ponzies.txt'
  docs: './Docs'
