config:
  ponzi_ast_location: '~/PycharmProjects/ast_generator/Ponzi_Abstract_Syntax_Trees'
  not_ponzi_ast_location: '~/PycharmProjects/ast_generator/Not_Smart_Ponzi_AST'
  not_smart_ponzi_source_code: '~/PycharmProjects/ast_generator/Not_Smart_Ponzi_Source_Code'
  smart_ponzi_source_code: '~/PycharmProjects/ast_generator/Smart_Ponzi'
  ponzi_csv: '~/PycharmProjects/ast_generator/Docs/ponzi.csv'
  not_ponzi_csv: '~/PycharmProjects/ast_generator/Docs/not_ponzi.csv'
  contracts_csv: '~/PycharmProjects/ast_generator/Docs/contracts.csv'
  contracts2_csv: '~/PycharmProjects/ast_generator/Docs/contracts2.csv'
  not_ponzi_semantic_documents: '~/PycharmProjects/ast_generator/Docs/Not_Ponzi_Semantic_Documents'
  ponzi_semantic_documents: '~/PycharmProjects/ast_generator/Docs/Ponzi_Semantic_Documents'
  most_used_in_ponzies: '~/PycharmProjects/ast_generator/Docs/Most_used_terms_in_Ponzies.txt'
  most_used_in_not_ponzies: '~/PycharmProjects/ast_generator/Docs/Most_used_terms_in_Not_Ponzies.txt'
  docs: '~/PycharmProjects/ast_generator/Docs'